name: Deploy GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  jekyll:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          npm install
          npm run build
      - name: Publish parser on GitHub Pages
        run: |
          mkdir docs
          cp -r src docs
          echo "# Treesitter Groovy Sdl Publish Page" >> docs/README.md
      - name: 🚀 deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages

